import "./globals.css";

import { Inter } from "next/font/google";

import BoardProvider from "@/contexts/BoardContext";
import SidebarProvider from "@/contexts/SidebarContext";

import ColumnsProvider from "@/contexts/ColumnsContext";
import { AuthContextProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <UserProvider> */}
        <AuthContextProvider>
          <SidebarProvider>
            <BoardProvider>
              <ColumnsProvider>{children}</ColumnsProvider>
            </BoardProvider>
          </SidebarProvider>
        </AuthContextProvider>
        {/* </UserProvider> */}
      </body>
    </html>
  );
}
