import "./globals.css";

import { Inter } from "next/font/google";

import BoardProvider from "@/contexts/BoardContext";
import SidebarProvider from "@/contexts/SidebarContext";

import TopNavBar from "@/components/TopNavBar";
import SideBar from "@/components/SideBar";
import Footer from "@/components/Footer";
import ColumnsProvider from "@/contexts/ColumnsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <BoardProvider>
            <ColumnsProvider>
              <TopNavBar />
              <SideBar />
              {children}
              <Footer />
            </ColumnsProvider>
          </BoardProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
